title: "Hrishav Bhattarai"
email: "398hrishav@gmail.com"
description: "Data Analyst | M.S. in CSE | Python, SQL, Power BI | Transforming Data into Strategic Insights"

baseurl: "" # leave blank for root
url: "https://hrishav398.com.np"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-remote-theme

sass:
  style: compressed

include:
  - assets/css

show_nav: true

navigation:
  - title: "Home"
    url: /
  - title: "Experience"
    url: /experience/
  - title: "Projects"
    url: /projects/
  - title: "Publications"
    url: /publications/


author:
  name: "Hrishav Bhattarai"
  avatar: "/assets/images/profile.jpg"
  bio: "Data Analyst; M.S. in CSE; Python, SQL, Power BI; Transforming Data into Strategic Insights"
  location: "USA"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:398hrishav@gmail.com"
 
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/398hrishav"
   
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/hrishav398"
    
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=57pf-1IAAAAJ"
    

# Enable sidebar author profile
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true


