title: "Hrishav Bhattarai"
email: "398hrishav@gmail.com"
description: >-
  Data Scientist | AI/ML Enthusiast | M.S. in CSE
baseurl: ""
url: "https://hrishav398.com.np"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-remote-theme

author:
  name: "Hrishav Bhattarai"
  avatar: "/assets/images/profile.jpg"
  bio: "Exploring opportunities in Data Science, AI/ML"
  location: "USA"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:398hrishav@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/398hrishav"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/hrishav398"

   
 
      

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true

# Navigation
nav:
  - title: "Home"
    url: /
  - title: "Experience"
    url: /experience/
  - title: "Projects"
    url: /projects/
  - title: "Publications"
    url: /publications/
